# rustfmt configuration (stable options only)
# https://rust-lang.github.io/rustfmt/

edition = "2024"
max_width = 100
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
